name: EIP Audit

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    audit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run EIP audit
              run: python -m scripts.eip_audit
